require_relative './new_movies/version'
require_relative './new_movies/CLI'
require_relative './new_movies/movie'
require_relative './new_movies/cinemark_scraper'
require 'pry'
require 'nokogiri'
require 'open-uri'
